name: Build and publish images
on:
  push:
    branches:
      - main

jobs:
  build-mail:
    name: âœ‰ï¸Build mail service
    runs-on: ubuntu-22.04
    env:
      IMG_NAME: '${{github.repository}}-mail'
      IMG_PROJECT: 'warehouse-backend'
      IMG_REGISTRY: 'registry.warehousai.com'
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'

          file: ./dockerfiles/mail.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{env.IMG_PROJECT}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}

  build-user:
    name: ðŸ˜Build user service
    runs-on: ubuntu-22.04
    env:
      IMG_NAME: '${{github.repository}}-user'
      IMG_PROJECT: 'warehouse-backend'
      IMG_REGISTRY: 'registry.warehousai.com'
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'
          file: ./dockerfiles/user.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{env.IMG_PROJECT}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}

  build-ai:
    name: ðŸ¤–Build ai service
    runs-on: ubuntu-22.04
    env:
      IMG_NAME: '${{github.repository}}-ai'
      IMG_PROJECT: 'warehouse-backend'
      IMG_REGISTRY: 'registry.warehousai.com'
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'
          file: ./dockerfiles/ai.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{env.IMG_PROJECT}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}

  build-auth:
    name: ðŸ”‘Build auth service
    runs-on: ubuntu-22.04
    env:
      IMG_NAME: '${{github.repository}}-auth'
      IMG_PROJECT: 'warehouse-backend'
      IMG_REGISTRY: 'registry.warehousai.com'
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'
          file: ./dockerfiles/auth.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{env.IMG_PROJECT}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}

  build-stat:
    name: ðŸ“ˆBuild stat service
    runs-on: ubuntu-22.04
    env:
      IMG_NAME: '${{github.repository}}-stat'
      IMG_PROJECT: 'warehouse-backend'
      IMG_REGISTRY: 'registry.warehousai.com'
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'
          file: ./dockerfiles/stat.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{env.IMG_PROJECT}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}

  send-webhook:
    name: ðŸ“¨Notify the backend server
    runs-on: ubuntu-22.04
    needs: [build-auth, build-user, build-ai, build-mail, build-stat]
    steps:
      - uses: actions/checkout@v2

      - name: Send webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
